CREATE OR REPLACE VIEW public.trazabilidad_dia AS
 SELECT t.proceso,
    t.h6,
    t.h7,
    t.h8,
    t.h9,
    t.h10,
    t.h11,
    t.h12,
    t.h13,
    t.h14,
    t.h15,
    t.h16,
    t.h17,
    t.total_dia,
    t.promedio,
    t.h18,
    t.h19,
    t.h20,
    t.h21,
    t.h22,
    t.h23
   FROM ( SELECT 'Linea 1'::text AS proceso,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 6::double precision) AS h6,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 7::double precision) AS h7,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 8::double precision) AS h8,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 9::double precision) AS h9,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 10::double precision) AS h10,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 11::double precision) AS h11,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 12::double precision) AS h12,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 13::double precision) AS h13,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 14::double precision) AS h14,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 15::double precision) AS h15,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 16::double precision) AS h16,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 17::double precision) AS h17,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision) AS total_dia,
            round(count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision)::numeric / 18::numeric, 2) AS promedio,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 18::double precision) AS h18,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 19::double precision) AS h19,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 20::double precision) AS h20,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 21::double precision) AS h21,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 22::double precision) AS h22,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 23::double precision) AS h23
           FROM trazabilidad_ms
          WHERE ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')::date = (now() AT TIME ZONE 'America/Bogota'::text)::date AND trazabilidad_ms.pintura_linea = 'Linea 1'::lineas_type
        UNION ALL
         SELECT 'Linea 2'::text AS proceso,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 6::double precision) AS h6,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 7::double precision) AS h7,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 8::double precision) AS h8,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 9::double precision) AS h9,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 10::double precision) AS h10,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 11::double precision) AS h11,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 12::double precision) AS h12,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 13::double precision) AS h13,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 14::double precision) AS h14,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 15::double precision) AS h15,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 16::double precision) AS h16,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 17::double precision) AS h17,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision) AS total_dia,
            round(count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision)::numeric / 18::numeric, 2) AS promedio,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 18::double precision) AS h18,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 19::double precision) AS h19,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 20::double precision) AS h20,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 21::double precision) AS h21,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 22::double precision) AS h22,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 23::double precision) AS h23
           FROM trazabilidad_ms
          WHERE ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')::date = (now() AT TIME ZONE 'America/Bogota'::text)::date AND trazabilidad_ms.pintura_linea = 'Linea 2'::lineas_type
        UNION ALL
         SELECT 'Total Pintura'::text AS proceso,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 6::double precision) AS h6,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 7::double precision) AS h7,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 8::double precision) AS h8,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 9::double precision) AS h9,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 10::double precision) AS h10,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 11::double precision) AS h11,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 12::double precision) AS h12,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 13::double precision) AS h13,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 14::double precision) AS h14,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 15::double precision) AS h15,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 16::double precision) AS h16,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 17::double precision) AS h17,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision) AS total_dia,
            round(count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision)::numeric / 18::numeric, 2) AS promedio,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 18::double precision) AS h18,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 19::double precision) AS h19,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 20::double precision) AS h20,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 21::double precision) AS h21,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 22::double precision) AS h22,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 23::double precision) AS h23
           FROM trazabilidad_ms
          WHERE ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')::date = (now() AT TIME ZONE 'America/Bogota'::text)::date
        UNION ALL
         SELECT 'Vaciado'::text AS proceso,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 6::double precision) AS h6,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 7::double precision) AS h7,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 8::double precision) AS h8,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 9::double precision) AS h9,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 10::double precision) AS h10,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 11::double precision) AS h11,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 12::double precision) AS h12,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 13::double precision) AS h13,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 14::double precision) AS h14,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 15::double precision) AS h15,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 16::double precision) AS h16,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 17::double precision) AS h17,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision) AS total_dia,
            round(count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision)::numeric / 18::numeric, 2) AS promedio,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 18::double precision) AS h18,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 19::double precision) AS h19,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 20::double precision) AS h20,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 21::double precision) AS h21,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 22::double precision) AS h22,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 23::double precision) AS h23
           FROM trazabilidad_ms
          WHERE ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')::date = (now() AT TIME ZONE 'America/Bogota'::text)::date
        UNION ALL
         SELECT 'Linea 3'::text AS proceso,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 6::double precision) AS h6,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 7::double precision) AS h7,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 8::double precision) AS h8,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 9::double precision) AS h9,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 10::double precision) AS h10,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 11::double precision) AS h11,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 12::double precision) AS h12,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 13::double precision) AS h13,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 14::double precision) AS h14,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 15::double precision) AS h15,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 16::double precision) AS h16,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 17::double precision) AS h17,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision) AS total_dia,
            round(count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision)::numeric / 18::numeric, 2) AS promedio,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 18::double precision) AS h18,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 19::double precision) AS h19,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 20::double precision) AS h20,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 21::double precision) AS h21,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 22::double precision) AS h22,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 23::double precision) AS h23
           FROM trazabilidad_ms
          WHERE ((trazabilidad_ms.pintura_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')::date = (now() AT TIME ZONE 'America/Bogota'::text)::date AND trazabilidad_ms.pintura_linea = 'Linea 3'::lineas_type
        UNION ALL
         SELECT 'Kg Vaciados'::text AS proceso,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 6::double precision), 0::numeric)::bigint AS h6,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 7::double precision), 0::numeric)::bigint AS h7,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 8::double precision), 0::numeric)::bigint AS h8,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 9::double precision), 0::numeric)::bigint AS h9,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 10::double precision), 0::numeric)::bigint AS h10,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 11::double precision), 0::numeric)::bigint AS h11,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 12::double precision), 0::numeric)::bigint AS h12,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 13::double precision), 0::numeric)::bigint AS h13,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 14::double precision), 0::numeric)::bigint AS h14,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 15::double precision), 0::numeric)::bigint AS h15,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 16::double precision), 0::numeric)::bigint AS h16,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 17::double precision), 0::numeric)::bigint AS h17,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision), 0::numeric)::bigint AS total_dia,
            round(COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision), 0::numeric) / 18::numeric, 2) AS promedio,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 18::double precision), 0::numeric)::bigint AS h18,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 19::double precision), 0::numeric)::bigint AS h19,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 20::double precision), 0::numeric)::bigint AS h20,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 21::double precision), 0::numeric)::bigint AS h21,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 22::double precision), 0::numeric)::bigint AS h22,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 23::double precision), 0::numeric)::bigint AS h23
           FROM trazabilidad_ms
          WHERE ((trazabilidad_ms.vaciado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')::date = (now() AT TIME ZONE 'America/Bogota'::text)::date
        UNION ALL
         SELECT 'Acabado'::text AS proceso,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 6::double precision) AS h6,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 7::double precision) AS h7,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 8::double precision) AS h8,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 9::double precision) AS h9,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 10::double precision) AS h10,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 11::double precision) AS h11,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 12::double precision) AS h12,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 13::double precision) AS h13,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 14::double precision) AS h14,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 15::double precision) AS h15,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 16::double precision) AS h16,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 17::double precision) AS h17,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision) AS total_dia,
            round(count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision)::numeric / 18::numeric, 2) AS promedio,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 18::double precision) AS h18,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 19::double precision) AS h19,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 20::double precision) AS h20,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 21::double precision) AS h21,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 22::double precision) AS h22,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 23::double precision) AS h23
           FROM trazabilidad_ms
          WHERE ((trazabilidad_ms.acabado_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')::date = (now() AT TIME ZONE 'America/Bogota'::text)::date
        UNION ALL
         SELECT 'CEDI'::text AS proceso,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 6::double precision) AS h6,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 7::double precision) AS h7,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 8::double precision) AS h8,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 9::double precision) AS h9,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 10::double precision) AS h10,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 11::double precision) AS h11,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 12::double precision) AS h12,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 13::double precision) AS h13,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 14::double precision) AS h14,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 15::double precision) AS h15,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 16::double precision) AS h16,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 17::double precision) AS h17,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision) AS total_dia,
            round(count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision)::numeric / 18::numeric, 2) AS promedio,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 18::double precision) AS h18,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 19::double precision) AS h19,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 20::double precision) AS h20,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 21::double precision) AS h21,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 22::double precision) AS h22,
            count(*) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 23::double precision) AS h23
           FROM trazabilidad_ms
          WHERE ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')::date = (now() AT TIME ZONE 'America/Bogota'::text)::date
        UNION ALL
         SELECT 'Kg CEDI'::text AS proceso,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 6::double precision), 0::numeric)::bigint AS h6,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 7::double precision), 0::numeric)::bigint AS h7,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 8::double precision), 0::numeric)::bigint AS h8,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 9::double precision), 0::numeric)::bigint AS h9,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 10::double precision), 0::numeric)::bigint AS h10,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 11::double precision), 0::numeric)::bigint AS h11,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 12::double precision), 0::numeric)::bigint AS h12,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 13::double precision), 0::numeric)::bigint AS h13,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 14::double precision), 0::numeric)::bigint AS h14,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 15::double precision), 0::numeric)::bigint AS h15,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 16::double precision), 0::numeric)::bigint AS h16,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 17::double precision), 0::numeric)::bigint AS h17,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision), 0::numeric)::bigint AS total_dia,
            round(COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) >= 6::double precision AND date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) <= 23::double precision), 0::numeric) / 18::numeric, 2) AS promedio,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 18::double precision), 0::numeric)::bigint AS h18,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 19::double precision), 0::numeric)::bigint AS h19,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 20::double precision), 0::numeric)::bigint AS h20,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 21::double precision), 0::numeric)::bigint AS h21,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 22::double precision), 0::numeric)::bigint AS h22,
            COALESCE(sum(trazabilidad_ms.kilos_vaciados) FILTER (WHERE date_part('hour'::text, ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')) = 23::double precision), 0::numeric)::bigint AS h23
           FROM trazabilidad_ms
          WHERE ((trazabilidad_ms.cedi_fecha AT TIME ZONE 'UTC') AT TIME ZONE 'America/Bogota')::date = (now() AT TIME ZONE 'America/Bogota'::text)::date) t;